---@alias AstrologyModeWeekType
---|`ASTROLOGY_WEEK_NARGOTT`
---|`ASTROLOGY_WEEK_SITHIS`
---|`ASTROLOGY_WEEK_AUOTOR`
---|`ASTROLOGY_WEEK_ARHYDEVI`
ASTROLOGY_WEEK_NARGOTT = 1
ASTROLOGY_WEEK_SITHIS = 2
ASTROLOGY_WEEK_AUOTOR = 3
ASTROLOGY_WEEK_ARHYDEVI = 4