spells_generation_core = {
    allowed_spells = {
        [MAGIC_SCHOOL_DESTRUCTIVE] = {
            SPELL_MAGIC_ARROW, SPELL_STONE_SPIKES,
            SPELL_ICE_BOLT, SPELL_LIGHTNING_BOLT, SPELL_FIREWALL,
            SPELL_FIREBALL, SPELL_FROST_RING,
            SPELL_METEOR_SHOWER, SPELL_CHAIN_LIGHTNING,
            SPELL_ARMAGEDDON, SPELL_IMPLOSION, SPELL_DEEP_FREEZE
        },
        [MAGIC_SCHOOL_LIGHT] = {
            SPELL_BLESS, SPELL_REGENERATION, SPELL_HASTE,
            SPELL_DEFLECT_ARROWS, SPELL_STONESKIN, SPELL_DISPEL,
            SPELL_BLOODLUST, SPELL_ANTI_MAGIC,
            SPELL_TELEPORT, SPELL_RESURRECT
        },
        [MAGIC_SCHOOL_DARK] = {
            SPELL_SLOW, SPELL_CURSE, SPELL_DISRUPTING_RAY,
            SPELL_WEAKNESS, SPELL_FORGETFULNESS, SPELL_PLAGUE,
            SPELL_BERSERK, SPELL_HYPNOTIZE,
            SPELL_VAMPIRISM, SPELL_BLIND
        },
        [MAGIC_SCHOOL_SUMMONING] = {
            SPELL_WASP_SWARM, SPELL_LAND_MINE, SPELL_MAGIC_FIST,
            SPELL_ARCANE_CRYSTAL, SPELL_SUMMON_ELEMENTALS,
            SPELL_PHANTOM, SPELL_BLADE_BARRIER,
            SPELL_SUMMON_HIVE, SPELL_CONJURE_PHOENIX,
            SPELL_CELESTIAL_SHIELD
        }
    }
}