---@alias PrepareStageDay
--- |`PREPARE_STAGE_LEVELING_DAY`
--- |`PREPARE_STAGE_SPECIAL_DAY`
--- |`PREPARE_STAGE_PREFIGHT_DAY`
--- |`PREPARE_STAGE_FIGHT_DAY`
PREPARE_STAGE_LEVELING_DAY = -1
PREPARE_STAGE_SPECIAL_DAY = -1
PREPARE_STAGE_PREFIGHT_DAY = -1
PREPARE_STAGE_FIGHT_DAY = -1