---@alias DraftDayType
---| `DRAFTS_SKIP_DAY`
---| `DRAFTS_START_DAY`
DRAFTS_SKIP_DAY = 1
DRAFTS_START_DAY = 2

---@alias DraftType
---| `DRAFT_TYPE_SIMPLE`
---| `DRAFT_TYPE_FAST`
---| `DRAFT_TYPE_HALF`
---| `DRAFT_TYPE_FIVE`
DRAFT_TYPE_SIMPLE = 1
DRAFT_TYPE_FAST = 2
DRAFT_TYPE_HALF = 3
DRAFT_TYPE_FIVE = 4