-- ѕеречень начальных значений ресурсов дл€ рас
INITIAL_RESOURCES = {
   [RACES.HAVEN] = {
     [WOOD] = 0,
     [ORE] = 0,
     [MERCURY] = 0,
     [CRYSTAL] = 0,
     [SULFUR] = 0,
     [GEM] = 0,
     [GOLD] = 130000,
   },
   [RACES.INFERNO] = {
     [WOOD] = 0,
     [ORE] = 0,
     [MERCURY] = 0,
     [CRYSTAL] = 0,
     [SULFUR] = 0,
     [GEM] = 0,
     [GOLD] = 130000,
   },
   [RACES.NECROPOLIS] = {
     [WOOD] = 0,
     [ORE] = 0,
     [MERCURY] = 0,
     [CRYSTAL] = 0,
     [SULFUR] = 0,
     [GEM] = 0,
     [GOLD] = 130000,
   },
   [RACES.SYLVAN] = {
     [WOOD] = 0,
     [ORE] = 0,
     [MERCURY] = 0,
     [CRYSTAL] = 0,
     [SULFUR] = 0,
     [GEM] = 0,
     [GOLD] = 130000,
   },
   [RACES.ACADEMY] = {
     [WOOD] = 0,
     [ORE] = 0,
     [MERCURY] = 0,
     [CRYSTAL] = 0,
     [SULFUR] = 0,
     [GEM] = 0,
     [GOLD] = 130000,
   },
   [RACES.DUNGEON] = {
     [WOOD] = 0,
     [ORE] = 0,
     [MERCURY] = 0,
     [CRYSTAL] = 0,
     [SULFUR] = 0,
     [GEM] = 0,
     [GOLD] = 130000,
   },
   [RACES.FORTRESS] = {
     [WOOD] = 0,
     [ORE] = 0,
     [MERCURY] = 0,
     [CRYSTAL] = 0,
     [SULFUR] = 0,
     [GEM] = 0,
     [GOLD] = 130000,
   },
   [RACES.STRONGHOLD] = {
     [WOOD] = 0,
     [ORE] = 0,
     [MERCURY] = 0,
     [CRYSTAL] = 0,
     [SULFUR] = 0,
     [GEM] = 0,
     [GOLD] = 130000,
   },
}